name: Report Training Error
about: Report a training error, and track investigation and mitigation advice from
  GitHub Engineering
title: "[Training Error]: "
labels: training-error
body:
  - type: markdown
    attributes:
      value: |
        Thank you participating in the copilot custom models beta! If you encounter any errors in training a custom model, please submit an issue here and our engineering team will investigate .
  - type: input
    attributes:
      label: Pipeline ID
      description: |
        The pipeline ID from the training run which encountered an error. This can be retrieved from the training details for the model, for example:
        `2024-08-23 18:42:50 Pipeline ID: 21082043-7f21-4d76-9211-52ed4c06f8b1, Stage ID: ba4d773e-b917-4f69-acfb-40813a018d05`
