name: Report Training Error
description: Report a training error, and track investigation and mitigation advice from
  GitHub Engineering
title: "[Training Error]: "
labels: training-error
body:
  - type: markdown
    attributes:
      value: |
        Thank you participating in the GitHub Copilot custom models beta!
        
        If you encounter any errors in training a custom model, please submit an issue here and our engineering team will investigate and provide guidance.
  - type: input
    id: pipeline
    attributes:
      label: Pipeline ID
      placeholder: "00000000-0000-0000-0000-000000000000"
      description: |
        The pipeline ID from the training run which encountered an error.
        <details>
        <summary>How do I find this?</summary>
        The pipeline ID for a training run is a UUID identifier unique to each training.
        You can find it by navigating to the training details page for the model training which failed, and viewing the training logs.
        An example log line may look like:
        
        `2024-08-23 18:42:50 Pipeline ID: 21082043-7f21-4d76-9211-52ed4c06f8b1, Stage ID: ba4d773e-b917-4f69-acfb-40813a018d05`

        You can also find this identifier in the URL for the training run.
        </details>
